/**
 * Type-generation engine for `amba types generate`.
 *
 * Reads every collection schema for a project from the admin API and
 * emits a single `.amba/types.d.ts` declaration body that augments the
 * `@layers/amba-client` and `@layers/amba-functions` modules so
 * `Amba.collections.<name>`, `client.collections.<name>`, and
 * `ctx.collections.<name>` are statically typed.
 */

export interface CodegenHttpClient {
  /** Minimal contract — the engine only needs GET. */
  get<T>(path: string): Promise<{ data: T }>;
}

export interface GenerateTypesInput {
  http: CodegenHttpClient;
  projectId: string;
  /** Optional banner timestamp for testing. Default: no timestamp (deterministic output). */
  bannerTimestamp?: string;
}

export interface GenerateTypesResult {
  /** Full content of `.amba/types.d.ts`. */
  declarationsTs: string;
  /** Names of every collection that was emitted. */
  collectionNames: string[];
}

interface ListResponse {
  data: Array<{ name: string }>;
}

interface DescribeColumn {
  column_name: string;
  data_type: string;
  is_nullable: 'YES' | 'NO';
  column_default: string | null;
}

interface DescribeResponse {
  data: {
    name: string;
    columns: DescribeColumn[];
  };
}

interface CollectionSchema {
  name: string;
  columns: DescribeColumn[];
}

/** Read every collection schema and emit a single `.amba/types.d.ts` body. */
export async function generateCollectionTypes(
  input: GenerateTypesInput,
): Promise<GenerateTypesResult> {
  const list = await listCollections(input.http, input.projectId);
  const sorted = [...list].sort();
  const collections: CollectionSchema[] = [];
  for (const name of sorted) {
    collections.push(await describeCollection(input.http, input.projectId, name));
  }
  return {
    declarationsTs: emitDeclarations(collections, input.bannerTimestamp),
    collectionNames: sorted,
  };
}

async function listCollections(http: CodegenHttpClient, projectId: string): Promise<string[]> {
  const { data } = await http.get<ListResponse>(
    `/admin/projects/${encodeURIComponent(projectId)}/collections?limit=200`,
  );
  return data.data.map((c) => c.name).filter((n): n is string => typeof n === 'string');
}

async function describeCollection(
  http: CodegenHttpClient,
  projectId: string,
  name: string,
): Promise<CollectionSchema> {
  const { data } = await http.get<DescribeResponse>(
    `/admin/projects/${encodeURIComponent(projectId)}/collections/${encodeURIComponent(name)}`,
  );
  return { name: data.data.name, columns: data.data.columns };
}

/**
 * Postgres `data_type` → TypeScript surface form. Names match the spelling
 * `information_schema.columns` returns.
 */
const PG_TYPE_TO_TS: Record<string, string> = {
  uuid: 'string',
  text: 'string',
  'character varying': 'string',
  integer: 'number',
  bigint: 'number',
  smallint: 'number',
  numeric: 'number',
  'double precision': 'number',
  real: 'number',
  boolean: 'boolean',
  'timestamp with time zone': 'string',
  'timestamp without time zone': 'string',
  date: 'string',
  jsonb: 'unknown',
  json: 'unknown',
};

function tsTypeForColumn(col: DescribeColumn): string {
  const base = PG_TYPE_TO_TS[col.data_type] ?? 'unknown';
  if (col.column_name === 'deleted_at') return 'string | null';
  if (col.is_nullable === 'YES') return `${base} | null`;
  return base;
}

const HEADER_BANNER = `// .amba/types.d.ts
// AUTO-GENERATED by \`amba types generate\` — do not edit by hand.
//
// This file is regenerated whenever you run the CLI. It declares one
// interface per customer collection and module-augments @layers/amba-client +
// @layers/amba-functions so \`Amba.collections.<name>\`, \`client.collections.<name>\`,
// and \`ctx.collections.<name>\` (Worker side) are all statically typed.
//
// Commit OR gitignore at your discretion. The shape mirrors your current
// schema — regenerate after every collection migration.`;

function emitDeclarations(collections: CollectionSchema[], bannerTimestamp?: string): string {
  const banner = bannerTimestamp
    ? `${HEADER_BANNER}\n// Generated: ${bannerTimestamp}`
    : HEADER_BANNER;

  const interfaces = collections.map((c) => emitInterface(c)).join('\n\n');

  const augmentClient = collections.length
    ? `
declare module '@layers/amba-client' {
  interface CollectionsRoot {
${collections.map((c) => `    readonly ${tsLiteralKey(c.name)}: import('@layers/amba-client').ClientCollection<Amba.collections.${tsTypeName(c.name)}>;`).join('\n')}
  }
}
`
    : '';

  const augmentFunctions = collections.length
    ? `
declare module '@layers/amba-functions' {
  interface CollectionsRoot {
${collections.map((c) => `    readonly ${tsLiteralKey(c.name)}: import('@layers/amba-functions').Collection<Amba.collections.${tsTypeName(c.name)}>;`).join('\n')}
  }
}
`
    : '';

  return `${banner}\n\nexport {};\n\ndeclare global {\n  namespace Amba {\n    namespace collections {\n${interfaces ? indent(interfaces, 6) : '      // (no collections defined yet)'}\n    }\n  }\n}\n${augmentClient}${augmentFunctions}`;
}

function emitInterface(c: CollectionSchema): string {
  const fields = c.columns.map((col) => {
    const ts = tsTypeForColumn(col);
    const optional = col.is_nullable === 'YES' ? '?' : '';
    return `${tsLiteralKey(col.column_name)}${optional}: ${ts};`;
  });
  return `interface ${tsTypeName(c.name)} {\n${fields.map((f) => `  ${f}`).join('\n')}\n}`;
}

function indent(s: string, n: number): string {
  const pad = ' '.repeat(n);
  return s
    .split('\n')
    .map((line) => (line.length === 0 ? '' : pad + line))
    .join('\n');
}

function tsLiteralKey(name: string): string {
  if (/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name)) return name;
  return JSON.stringify(name);
}

function tsTypeName(collectionName: string): string {
  if (!/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(collectionName)) {
    return JSON.stringify(collectionName);
  }
  return collectionName;
}
