import pc from 'picocolors';

export type SchemaFormat = 'json' | 'typescript';
export type SchemaDomain =
  | 'all'
  | 'achievements'
  | 'streaks'
  | 'xp'
  | 'leaderboards'
  | 'challenges'
  | 'content'
  | 'segments'
  | 'push';

export interface SchemaExportOptions {
  domain: SchemaDomain;
  format?: SchemaFormat;
}

// Domain schemas — a point-in-time developer aid. Consumers who need
// the authoritative type definitions should import them from the SDK.
interface DomainSchema {
  name: SchemaDomain;
  description: string;
  fields: Record<string, string>;
}

const SCHEMAS: Record<Exclude<SchemaDomain, 'all'>, DomainSchema> = {
  achievements: {
    name: 'achievements',
    description: 'Achievement definitions — unlocked when criteria are met.',
    fields: {
      id: 'string (uuid)',
      code: 'string — unique key per project',
      name: 'string',
      description: 'string | null',
      criteria: 'AchievementCriteria — event_name/count/props or custom',
      reward: '{ xp?: number; currency?: Record<string, number>; items?: string[] } | null',
      is_active: 'boolean',
      created_at: 'string (ISO 8601)',
    },
  },
  streaks: {
    name: 'streaks',
    description: 'Streak definitions (daily, weekly, custom cadences).',
    fields: {
      id: 'string (uuid)',
      code: 'string',
      name: 'string',
      description: 'string | null',
      cadence: "'daily' | 'weekly'",
      grace_period_days: 'number',
      is_active: 'boolean',
      created_at: 'string (ISO 8601)',
    },
  },
  xp: {
    name: 'xp',
    description: 'XP rules — award XP on matching events.',
    fields: {
      id: 'string (uuid)',
      event_name: 'string',
      amount: 'number',
      description: 'string | null',
      created_at: 'string (ISO 8601)',
    },
  },
  leaderboards: {
    name: 'leaderboards',
    description: 'Leaderboard definitions and entries.',
    fields: {
      id: 'string (uuid)',
      code: 'string',
      name: 'string',
      metric: "'xp' | 'streak' | 'custom'",
      period: "'all_time' | 'daily' | 'weekly' | 'monthly'",
      is_active: 'boolean',
      created_at: 'string (ISO 8601)',
    },
  },
  challenges: {
    name: 'challenges',
    description: 'Time-boxed user goals.',
    fields: {
      id: 'string (uuid)',
      code: 'string',
      name: 'string',
      goal_type: "'event_count' | 'xp_earned' | 'streak_maintained'",
      goal_value: 'number',
      starts_at: 'string (ISO 8601)',
      ends_at: 'string (ISO 8601)',
      reward: '{ xp?: number; items?: string[] } | null',
      created_at: 'string (ISO 8601)',
    },
  },
  content: {
    name: 'content',
    description: 'Content libraries, items, and schedules.',
    fields: {
      library_id: 'string (uuid)',
      slug: 'string — unique per project',
      name: 'string',
      description: 'string | null',
      item: '{ key: string; content: unknown; locale?: string }',
      schedule: '{ library_id: string; cron: string; channel: string; target?: SegmentTarget }',
      created_at: 'string (ISO 8601)',
    },
  },
  segments: {
    name: 'segments',
    description: 'User segments — predicate-based cohorts.',
    fields: {
      id: 'string (uuid)',
      name: 'string',
      description: 'string | null',
      rules: 'SegmentRule tree (all/any + property/cohort/date operators)',
      is_active: 'boolean',
      created_at: 'string (ISO 8601)',
    },
  },
  push: {
    name: 'push',
    description: 'Push campaigns and deliveries.',
    fields: {
      campaign_id: 'string (uuid)',
      name: 'string',
      title: 'string',
      body: 'string',
      schedule_cron: 'string | null',
      segment_id: 'string | null — null = all users',
      data: 'Record<string, unknown> | null',
      created_at: 'string (ISO 8601)',
    },
  },
};

function renderJson(domains: DomainSchema[]): string {
  return JSON.stringify(domains, null, 2) + '\n';
}

function renderTypescript(domains: DomainSchema[]): string {
  const lines: string[] = [
    '// Auto-generated by `amba schema export --format=typescript`.',
    '// For the canonical types, import from the @layers/amba-client SDK.',
    '',
  ];
  for (const d of domains) {
    lines.push(`// ${d.description}`);
    lines.push(`export interface ${pascal(d.name)} {`);
    for (const [field, type] of Object.entries(d.fields)) {
      lines.push(`  /** ${type} */`);
      lines.push(`  ${field}: unknown;`);
    }
    lines.push('}');
    lines.push('');
  }
  return lines.join('\n');
}

function pascal(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

export async function schemaExportCommand(opts: SchemaExportOptions): Promise<void> {
  const domain = opts.domain;
  const format: SchemaFormat = opts.format ?? 'json';

  const available = Object.keys(SCHEMAS);
  if (domain !== 'all' && !available.includes(domain)) {
    console.log();
    console.log(pc.red('  ✗') + ` Unknown domain: ${domain}`);
    console.log(pc.dim(`    Valid: all, ${available.join(', ')}`));
    console.log();
    process.exit(1);
  }

  if (format !== 'json' && format !== 'typescript') {
    console.log();
    console.log(pc.red('  ✗') + ` Unknown --format: ${String(format)}`);
    console.log(pc.dim('    Valid: json, typescript'));
    console.log();
    process.exit(1);
  }

  const selected: DomainSchema[] =
    domain === 'all' ? Object.values(SCHEMAS) : [SCHEMAS[domain as Exclude<SchemaDomain, 'all'>]];

  const output = format === 'json' ? renderJson(selected) : renderTypescript(selected);
  process.stdout.write(output);
}
